### PR TITLE
Check for _.result in 'ensure' contract linting

### PR DESCRIPTION
**Pull request by rpdelaney**
Previously, using `_` in a `@deal.ensure` contract validator would lead to this error:

```console
$ python3 -m deal lint
dumbpw/pwgen.py
  32:4 DEAL002 ensure contract must have `result` arg
    lambda _: len(_.result) == _.length,
    ^
```

This change fixes that false positive by detecting when the arg name is `_` and passing the lint check if `_.result` is anywhere in the validator body.

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you. Tests, please.

**Comment by rpdelaney** [comment]
It seems this project supports python>=3.7? Unfortunately `ast.unparse()` is not supported until 3.9. I have a test that seems to work with `asteroid` but I'm not exactly a wizard with the `ast` module. But I'm learning. Hopefully I'll have something more soon.

**Comment by rpdelaney** [comment]
Okay, how's that? 😬

**Comment by orsinium** [comment]
Thank you for working on this 👍🏿 Yep, good enough, I can improve on it later (I think we could move it into extractors and use `get_name` function there). Please, fix flake8, merge master into your branch (I've fixed mypy there), and I'll merge it. CI matters.

**Comment by rpdelaney** [comment]
>  CI matters.

Of course. I think pre-commit has made me lazy :)

Flake8's W503 and W504 are in conflict with each other. I think the best resolution there is to silence one of them -- I prefer to kill W503 myself, but let me know how you want to proceed.

**Comment by orsinium** [comment]
It's ok, I'll take it from there.

**Comment by orsinium** [comment]
Thank you for your help :)

**Comment by rpdelaney** [comment]
Argh:

```diff
diff --git c/dumbpw/engine.py i/dumbpw/engine.py
index 590a99b..dfed239 100644
--- c/dumbpw/engine.py
+++ i/dumbpw/engine.py
@@ -99,7 +99,7 @@ def search(
     message="length must be greater than zero.",
 )
 @deal.pre(
-    validator=lambda charset, length: len("".join(charset)) > 0,
+    validator=lambda _: len("".join(_.charset)) > 0,
     message="charset must have positive len.",
 )
 @deal.ensure(
@@ -107,9 +107,7 @@ def search(
     message="The returned value len must equal the requested length.",
 )
 @deal.ensure(
-    validator=lambda charset, length, result: all(
-        char in "".join(charset) for char in result
-    ),
+    validator=lambda _: all(char in "".join(_.charset) for char in _.result),
     message="function return value must be "
     "composed of characters in the charset",
 )
```

```console
$ flake8 dumbpw/engine.py
Traceback (most recent call last):
  File "/Users/ryan/src/me/dumbpw/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 364, in _run
    self.run_checks()
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/checker.py", line 311, in run
    self.run_serial()
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/checker.py", line 295, in run_serial
    checker.run_checks()
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/flake8/checker.py", line 500, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/deal/linter/_checker.py", line 32, in run
    for error in self.get_errors():
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/deal/linter/_checker.py", line 49, in get_errors
    for error in rule(func=func, stubs=self._stubs):
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/deal/linter/_rules.py", line 89, in __call__
    yield from self._check(contract)
  File "/Users/ryan/src/me/dumbpw/.venv/lib/python3.10/site-packages/deal/linter/_rules.py", line 92, in _check
    validator = contract.args[0]
IndexError: tuple index out of range
```

**Comment by orsinium** [comment]
Try passing the validator as a positional arg.

**Comment by rpdelaney** [comment]
That is... not the fix I expected :monocle_face:

**Pull request merged**
