### PR TITLE
Add @deal.ensure decorator (Fixes #11)

### LINKED ISSUE #11: @ensure
Combination of `@pre` and `@post`. 

1. Called after function call
2. asses args, kwargs and `result` keyword argument with function result.
3. Raises `PostConditionError` on contract violation.

That's `@post` that can use data from function arguments.

Example:

```python
@deal.ensure(lambda a, b, result: abs(a) < abs(b) or abs(result) >= 1)
@deal.ensure(lambda a, b, result: abs(a) >= (b) or result < 1)
def div(a, b):
  return a / b
```

### PR DESCRIPTION
**Pull request by spencerwi**

### CODE REVIEW

**Comment by spencerwi** [comment]
I noticed several other tests are failing already -- looking at CI build history, it seems like they were already failing? I can at least confirm that the tests for this decorator are passing.

**Comment by orsinium** [comment]
Wow, that was fast! Thank you. I'll take care of CI :+1:

**Comment by orsinium** [comment]
Oh, wait, no. Ugh, that's from master, right.

**Comment by orsinium** [comment]
I can't push in master of your fork. So, PR is moved into #14 with a new branch.

**Pull request merged**
