### PR TITLE
Add note about `...import annotations` error

### PR DESCRIPTION
**Pull request by pianoJames**

### CODE REVIEW

**Comment by pianoJames** [comment]
Hello!
This is definitely NOT the right way to fix this, but I think you have "issues" disabled on this repo (?) :wink: 

I created this PR because I'd like to know if you think this is fixable _at all_ for Python3.7.

If it is (or might be), I'm willing to attempt an actual fix. If you're pretty sure it's not, then I'll spend my time elsewhere.

Thanks for the feedback!

**Comment by pianoJames** [comment]
Further info:
1. Run  `python3 -m deal test repro_example.py` (where `repro_example.py` contains the code below)
2. While running, on [this line in `_contracts.py`](https://github.com/life4/deal/blob/e39f52c5a309f0616ee9290479cbbbf86ddd555d/deal/_runtime/_contracts.py#L127), it appears that both  `args` and `kwargs` are empty.
3. If you remove the `from __future__ import annotations` from `repro_example.py` below, then `kwargs` won't be empty. It will instead be what it should be, for example, `{'x': []}` or `{'x': [1, 2, 3]}`.

I may have some time another day to dig deeper, but hopefully this will help to judge how feasible a fix might be.

```python3
from __future__ import annotations
import deal
from typing import List


@deal.has()
def append_one(x: List[int]) -> List[int]:
    x.append(1)
    return x
```

**Comment by orsinium** [comment]
Sorry, [Python 3.7 has reached EoL](https://devguide.python.org/versions/), and deal won't support it anymore. I'll make sure to update CI and constraints. Thanks for reaching out.

**Comment by pianoJames** [comment]
It didn't even cross my mind to check that, haha! Thanks for letting me know.

**Pull request closed without merging**
